# Workflow name
name: Build app
on:
  # Trigger on every pull request and on push
  # to the `main` branch.
  pull_request:
  push:
    branches:
      - master

# Where will they run
jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Extract GOOGLE_SERVICES_JSON
        shell: bash
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json
      - name: Setup JDK - Temurin 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build APK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :app:assembleDebug
      - name: Check format and deps
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dependencyUpdates spotlessCheck
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: UnitConverter.apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload Dependencies report
        uses: actions/upload-artifact@v3
        with:
          name: dependencyUpdates.txt
          path: build/dependencyUpdates/report.txt
